# Generated by Django 4.2.4 on 2023-09-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_sale_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
